//! git(1): the subcommands that only report, and the options they share.
//!
//! `--output`, `-o`, `--ext-diff`, `--textconv` and friends are absent on
//! purpose: they write files or run repository-configured programs.

use super::super::scan::Getopt;

/// `git` subcommands that only report. `--version` is admitted here so a
/// probe needs no separate rule; `-c`/`--exec-path`-style git-level
/// options are refused because they are not subcommands.
pub(in crate::perms::read_only) const GIT_SUBCOMMANDS: &[&str] = &[
    "status",
    "log",
    "diff",
    "show",
    "blame",
    "rev-parse",
    "describe",
    "ls-files",
    "--version",
];

/// Reporting options shared by those subcommands. `--output`, `-o`,
/// `--ext-diff`, `--textconv` and friends are absent on purpose: they
/// write files or run repository-configured programs.
pub(in crate::perms::read_only) const GIT_OPTS: Getopt = Getopt {
    flags: "psuwMCRz",
    valued: "nLSG",
    longs: &[
        "oneline",
        "stat",
        "numstat",
        "shortstat",
        "name-only",
        "name-status",
        "summary",
        "patch",
        "no-patch",
        "raw",
        "graph",
        "decorate",
        "no-decorate",
        "all",
        "branches",
        "tags",
        "remotes",
        "first-parent",
        "merges",
        "no-merges",
        "reverse",
        "follow",
        "since",
        "until",
        "author",
        "committer",
        "grep",
        "pretty",
        "format",
        "date",
        "abbrev-commit",
        "no-abbrev-commit",
        "abbrev-ref",
        "short",
        "long",
        "porcelain",
        "cached",
        "staged",
        "word-diff",
        "unified",
        "find-renames",
        "no-renames",
        "diff-filter",
        "max-count",
        "skip",
        "topo-order",
        "date-order",
        "relative",
        "no-relative",
        "ignore-all-space",
        "ignore-space-change",
        "no-ext-diff",
        "no-textconv",
        "color",
        "no-color",
        "branch",
        "untracked-files",
        "ignored",
        "others",
        "modified",
        "deleted",
        "exclude-standard",
        "full-name",
        "stage",
        "show-toplevel",
        "git-dir",
        "is-inside-work-tree",
        "verify",
        "quiet",
        "line-porcelain",
        "root",
        "boundary",
        "contains",
        "dirty",
        "always",
    ],
    valued_longs: &[],
    digits: true,
};
