//! Search and display readers: ripgrep and bat.
//!
//! Both grow options that run other programs, so both are listed rather
//! than trusted wholesale.

use super::super::scan::Getopt;

/// ripgrep, minus `--pre`/`--pre-glob` (runs a preprocessor program),
/// `-z`/`--search-zip` (runs decompressors) and `--hostname-bin`.
pub(in crate::perms::read_only) const RG_OPTS: Getopt = Getopt {
    flags: "iIsSnNvwxucFLUpqaoPhV0",
    valued: "eABCgtTmMfj",
    longs: &[
        "hidden",
        "no-ignore",
        "no-ignore-vcs",
        "glob",
        "iglob",
        "glob-case-insensitive",
        "type",
        "type-not",
        "type-list",
        "files",
        "files-with-matches",
        "files-without-match",
        "count",
        "count-matches",
        "line-number",
        "no-line-number",
        "column",
        "heading",
        "no-heading",
        "context",
        "after-context",
        "before-context",
        "context-separator",
        "max-count",
        "max-columns",
        "max-columns-preview",
        "max-depth",
        "max-filesize",
        "fixed-strings",
        "word-regexp",
        "line-regexp",
        "smart-case",
        "ignore-case",
        "case-sensitive",
        "multiline",
        "multiline-dotall",
        "pcre2",
        "engine",
        "json",
        "null",
        "null-data",
        "only-matching",
        "replace",
        "sort",
        "sortr",
        "stats",
        "trim",
        "vimgrep",
        "color",
        "colors",
        "no-filename",
        "with-filename",
        "include-zero",
        "invert-match",
        "regexp",
        "file",
        "threads",
        "follow",
        "binary",
        "text",
        "unrestricted",
        "no-config",
        "no-messages",
        "no-require-git",
        "one-file-system",
        "quiet",
        "crlf",
        "encoding",
        "path-separator",
    ],
    valued_longs: &[],
    digits: false,
};

/// bat, minus `--pager` (runs an arbitrary pager command).
pub(in crate::perms::read_only) const BAT_OPTS: Getopt = Getopt {
    flags: "npAfLu",
    valued: "lrHm",
    longs: &[
        "plain",
        "number",
        "show-all",
        "language",
        "list-languages",
        "list-themes",
        "theme",
        "style",
        "color",
        "paging",
        "wrap",
        "terminal-width",
        "decorations",
        "italic-text",
        "tabs",
        "line-range",
        "highlight-line",
        "map-syntax",
        "file-name",
        "squeeze-blank",
        "chop-long-lines",
        "nonprintable-notation",
    ],
    valued_longs: &[],
    digits: false,
};
