//! The audited option surfaces: for each command whose options are *not*
//! uniformly inert, the exact forms proven neither to execute a program
//! nor to write a file.
//!
//! Kept apart from `table` because these change for a different reason —
//! a command grows a new flag, or a manual is re-read — and because every
//! omission here is load-bearing: a form that is absent is refused, which
//! is how `rg --pre`, `bat --pager` and `sort --compress-program` stay
//! out of a proof without anyone having to enumerate the dangerous forms.

use super::scan::Getopt;

/// `git` subcommands that only report. `--version` is admitted here so a
/// probe needs no separate rule; `-c`/`--exec-path`-style git-level
/// options are refused because they are not subcommands.
pub(super) const GIT_SUBCOMMANDS: &[&str] = &[
    "status",
    "log",
    "diff",
    "show",
    "blame",
    "rev-parse",
    "describe",
    "ls-files",
    "--version",
];

/// Reporting options shared by those subcommands. `--output`, `-o`,
/// `--ext-diff`, `--textconv` and friends are absent on purpose: they
/// write files or run repository-configured programs.
pub(super) const GIT_OPTS: Getopt = Getopt {
    flags: "psuwMCRz",
    valued: "nLSG",
    longs: &[
        "oneline",
        "stat",
        "numstat",
        "shortstat",
        "name-only",
        "name-status",
        "summary",
        "patch",
        "no-patch",
        "raw",
        "graph",
        "decorate",
        "no-decorate",
        "all",
        "branches",
        "tags",
        "remotes",
        "first-parent",
        "merges",
        "no-merges",
        "reverse",
        "follow",
        "since",
        "until",
        "author",
        "committer",
        "grep",
        "pretty",
        "format",
        "date",
        "abbrev-commit",
        "no-abbrev-commit",
        "abbrev-ref",
        "short",
        "long",
        "porcelain",
        "cached",
        "staged",
        "word-diff",
        "unified",
        "find-renames",
        "no-renames",
        "diff-filter",
        "max-count",
        "skip",
        "topo-order",
        "date-order",
        "relative",
        "no-relative",
        "ignore-all-space",
        "ignore-space-change",
        "no-ext-diff",
        "no-textconv",
        "color",
        "no-color",
        "branch",
        "untracked-files",
        "ignored",
        "others",
        "modified",
        "deleted",
        "exclude-standard",
        "full-name",
        "stage",
        "show-toplevel",
        "git-dir",
        "is-inside-work-tree",
        "verify",
        "quiet",
        "line-porcelain",
        "root",
        "boundary",
        "contains",
        "dirty",
        "always",
    ],
    digits: true,
};

/// ripgrep, minus `--pre`/`--pre-glob` (runs a preprocessor program),
/// `-z`/`--search-zip` (runs decompressors) and `--hostname-bin`.
pub(super) const RG_OPTS: Getopt = Getopt {
    flags: "iIsSnNvwxucFLUpqaoPhV0",
    valued: "eABCgtTmMfj",
    longs: &[
        "hidden",
        "no-ignore",
        "no-ignore-vcs",
        "glob",
        "iglob",
        "glob-case-insensitive",
        "type",
        "type-not",
        "type-list",
        "files",
        "files-with-matches",
        "files-without-match",
        "count",
        "count-matches",
        "line-number",
        "no-line-number",
        "column",
        "heading",
        "no-heading",
        "context",
        "after-context",
        "before-context",
        "context-separator",
        "max-count",
        "max-columns",
        "max-columns-preview",
        "max-depth",
        "max-filesize",
        "fixed-strings",
        "word-regexp",
        "line-regexp",
        "smart-case",
        "ignore-case",
        "case-sensitive",
        "multiline",
        "multiline-dotall",
        "pcre2",
        "engine",
        "json",
        "null",
        "null-data",
        "only-matching",
        "replace",
        "sort",
        "sortr",
        "stats",
        "trim",
        "vimgrep",
        "color",
        "colors",
        "no-filename",
        "with-filename",
        "include-zero",
        "invert-match",
        "regexp",
        "file",
        "threads",
        "follow",
        "binary",
        "text",
        "unrestricted",
        "no-config",
        "no-messages",
        "no-require-git",
        "one-file-system",
        "quiet",
        "crlf",
        "encoding",
        "path-separator",
    ],
    digits: false,
};

/// bat, minus `--pager` (runs an arbitrary pager command).
pub(super) const BAT_OPTS: Getopt = Getopt {
    flags: "npAfLu",
    valued: "lrHm",
    longs: &[
        "plain",
        "number",
        "show-all",
        "language",
        "list-languages",
        "list-themes",
        "theme",
        "style",
        "color",
        "paging",
        "wrap",
        "terminal-width",
        "decorations",
        "italic-text",
        "tabs",
        "line-range",
        "highlight-line",
        "map-syntax",
        "file-name",
        "squeeze-blank",
        "chop-long-lines",
        "nonprintable-notation",
    ],
    digits: false,
};

/// sort, minus `-o`/`--output` (writes) and `--compress-program`,
/// `--random-source`, `--temporary-directory` (run or create files).
pub(super) const SORT_OPTS: Getopt = Getopt {
    flags: "bdfghiMnrRsuVzcC",
    valued: "kt",
    longs: &[
        "ignore-leading-blanks",
        "dictionary-order",
        "ignore-case",
        "general-numeric-sort",
        "ignore-nonprinting",
        "month-sort",
        "human-numeric-sort",
        "numeric-sort",
        "reverse",
        "random-sort",
        "sort",
        "stable",
        "unique",
        "version-sort",
        "zero-terminated",
        "check",
        "merge",
        "parallel",
        "field-separator",
        "key",
        "debug",
    ],
    digits: false,
};

/// tree, minus `-o` (writes its listing to a file).
pub(super) const TREE_OPTS: Getopt = Getopt {
    flags: "adfghlnpqrstuvxACDFJQSUX",
    valued: "LPI",
    longs: &[
        "dirsfirst",
        "filelimit",
        "noreport",
        "charset",
        "du",
        "timefmt",
        "prune",
        "inodes",
        "device",
        "sort",
        "gitignore",
        "level",
        "json",
        "version",
        "help",
    ],
    digits: false,
};

/// find, minus every action that runs a command (`-exec`, `-execdir`,
/// `-ok`, `-okdir`), deletes (`-delete`) or writes a file (`-fprint`,
/// `-fprint0`, `-fprintf`, `-fls`).
pub(super) const FIND_PRIMARIES: &[&str] = &[
    "-H",
    "-L",
    "-P",
    "-maxdepth",
    "-mindepth",
    "-depth",
    "-mount",
    "-xdev",
    "-follow",
    "-name",
    "-iname",
    "-path",
    "-ipath",
    "-wholename",
    "-iwholename",
    "-regex",
    "-iregex",
    "-regextype",
    "-lname",
    "-ilname",
    "-type",
    "-xtype",
    "-size",
    "-empty",
    "-newer",
    "-newermt",
    "-anewer",
    "-cnewer",
    "-mtime",
    "-mmin",
    "-ctime",
    "-cmin",
    "-atime",
    "-amin",
    "-user",
    "-group",
    "-uid",
    "-gid",
    "-nouser",
    "-nogroup",
    "-perm",
    "-inum",
    "-links",
    "-samefile",
    "-readable",
    "-writable",
    "-executable",
    "-true",
    "-false",
    "-not",
    "-a",
    "-and",
    "-o",
    "-or",
    "-prune",
    "-quit",
    "-print",
    "-print0",
    "-printf",
    "-ls",
];

/// date, minus `-s`/`--set` (sets the system clock).
pub(super) const DATE_OPTS: Getopt = Getopt {
    flags: "uR",
    valued: "dfr",
    longs: &[
        "utc",
        "universal",
        "rfc-3339",
        "rfc-email",
        "iso-8601",
        "date",
        "file",
        "reference",
        "debug",
    ],
    digits: false,
};
