use std::path::PathBuf;
use std::time::Duration;

use serde_json::Value;
use tempfile::TempDir;
use z_engine_core::agent::{
    ApprovalDecision, Event, LoopConfig, PermissionMode, spawn_with_recorder,
};
use z_engine_core::session::{SessionEvent, SessionWriter, read_events};
use z_engine_core::verification::{TaskReport, TaskStatus};

use super::verification_provider::{CANCEL_MARKER, Provider, Step};

pub const GOAL: &str = "Fix answer() to return 42 and verify the complete Rust workspace.";

const MANIFEST: &str = r#"[package]
name = "verification-fixture"
version = "0.1.0"
edition = "2021"

[workspace]
"#;

const LOCK: &str = r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "verification-fixture"
version = "0.1.0"
"#;

const SOURCE: &str = r#"pub fn answer() -> u32 {
    41
}

#[cfg(test)]
mod tests {
    #[test]
    fn answers_the_original_goal() {
        assert_eq!(super::answer(), 42);
    }
}
"#;

pub struct Fixture {
    _directory: TempDir,
    pub workspace: PathBuf,
    pub session: PathBuf,
    output: PathBuf,
}

impl Fixture {
    pub fn new() -> Self {
        // Keep all test-owned files inside the checkout, never the system temp directory.
        let directory = tempfile::Builder::new()
            .prefix(".verification-")
            .tempdir_in(".")
            .unwrap();
        let root = directory.path().canonicalize().unwrap();
        let workspace = root.join("workspace");
        std::fs::create_dir_all(workspace.join("src")).unwrap();
        std::fs::create_dir_all(workspace.join(".cargo")).unwrap();
        std::fs::create_dir_all(root.join("sessions")).unwrap();
        std::fs::write(workspace.join("Cargo.toml"), MANIFEST).unwrap();
        std::fs::write(workspace.join("Cargo.lock"), LOCK).unwrap();
        std::fs::write(workspace.join("src/lib.rs"), SOURCE).unwrap();
        std::fs::write(
            workspace.join(".cargo/config.toml"),
            "[net]\noffline = true\n",
        )
        .unwrap();
        Self {
            _directory: directory,
            workspace,
            session: root.join("sessions/task.jsonl"),
            output: root.join("tool-output"),
        }
    }

    pub async fn run(&self, steps: Vec<Step>, record: bool, deny_verification: bool) -> Observed {
        self.run_with_denial(steps, record, deny_verification.then_some(0))
            .await
    }

    pub async fn run_with_denial(
        &self,
        steps: Vec<Step>,
        record: bool,
        deny_after: Option<usize>,
    ) -> Observed {
        self.run_options(steps, record, deny_after, false, 0).await
    }

    pub async fn run_aborting_finalization(&self, steps: Vec<Step>) -> Observed {
        self.run_options(steps, true, None, true, 0).await
    }

    #[allow(dead_code)]
    pub async fn run_supervised(
        &self,
        steps: Vec<Step>,
        continuations: u32,
        deny_after: Option<usize>,
    ) -> Observed {
        self.run_options(steps, true, deny_after, false, continuations)
            .await
    }

    async fn run_options(
        &self,
        steps: Vec<Step>,
        record: bool,
        deny_after: Option<usize>,
        cancel_finalization: bool,
        max_task_continuations: u32,
    ) -> Observed {
        let provider = Provider::start(steps).await;
        let mut auto_allow_tools = vec!["edit_file".into(), "write_file".into()];
        if deny_after.is_none() {
            auto_allow_tools.push("run_verification".into());
        }
        let config = LoopConfig {
            model: "verification-test-model".into(),
            base_url: provider.base_url.clone(),
            api_key: Some("local-fixture-not-a-secret".into()),
            project_root: self.workspace.clone(),
            tmp_dir: self.output.clone(),
            initial_allow_rules: Vec::new(),
            max_context_tokens: 100_000,
            max_output_tokens: 16_384,
            hooks: Default::default(),
            compact_at_percent: 92,
            keep_recent_messages: 12,
            review_enabled: false,
            max_task_continuations,
            mcp_servers: Vec::new(),
            auto_allow_tools,
            initial_mode: PermissionMode::Normal,
            shell_path: None,
        };
        let recorder = record.then(|| {
            let mut writer = SessionWriter::append_to(&self.session).unwrap();
            writer
                .record(&SessionEvent::Meta {
                    model: config.model.clone(),
                    project_root: self.workspace.to_string_lossy().into_owned(),
                })
                .unwrap();
            writer
        });
        let (handle, mut events) = spawn_with_recorder(config, None, recorder);
        handle.submit(GOAL);
        let mut observed = Vec::new();
        let mut verification_approvals = 0;
        let result = tokio::time::timeout(Duration::from_secs(120), async {
            loop {
                let event = events
                    .recv()
                    .await
                    .expect("agent ended before terminal event");
                if let Event::ApprovalRequired { id, tool, .. } = &event {
                    if tool == "run_verification"
                        && deny_after.is_some_and(|limit| verification_approvals >= limit)
                    {
                        handle.deny(*id);
                    } else {
                        handle.approve(*id, ApprovalDecision::Once);
                        if tool == "run_verification" {
                            verification_approvals += 1;
                        }
                    }
                }
                if matches!(&event, Event::TokenDelta(text) if text == CANCEL_MARKER) {
                    handle.abort();
                }
                if cancel_finalization
                    && matches!(&event, Event::StatusNote(text) if text == "Assessing task completion")
                {
                    handle.abort();
                }
                if let Event::TaskUpdated { report } = &event {
                    if report.status == TaskStatus::Complete {
                        assert!(record, "completion requires a durable recorder");
                        assert!(
                            read_events(&self.session).unwrap().contains(
                                &SessionEvent::TaskUpdated {
                                    report: Box::new(report.clone()),
                                }
                            ),
                            "completion was published before its durable record"
                        );
                    }
                }
                let terminal = matches!(
                    event,
                    Event::TurnCompleted { .. } | Event::TurnAborted | Event::Error(_)
                );
                observed.push(event);
                if terminal {
                    break;
                }
            }
        })
        .await;
        handle.shutdown();
        result.unwrap_or_else(|error| panic!("agent timed out: {error}; events: {observed:#?}"));
        tokio::time::timeout(Duration::from_secs(10), async {
            while let Some(event) = events.recv().await {
                observed.push(event);
            }
        })
        .await
        .expect("agent failed to shut down");
        provider.assert_consumed();
        let requests = provider.requests();
        let persisted = if record {
            read_events(&self.session).unwrap()
        } else {
            assert!(!self.session.exists());
            Vec::new()
        };
        assert_eq!(
            std::fs::read_to_string(self.workspace.join("Cargo.lock")).unwrap(),
            LOCK
        );
        Observed {
            events: observed,
            persisted,
            requests,
        }
    }
}

pub struct Observed {
    pub events: Vec<Event>,
    pub persisted: Vec<SessionEvent>,
    pub requests: Vec<Value>,
}

impl Observed {
    pub fn reports(&self) -> Vec<&TaskReport> {
        self.events
            .iter()
            .filter_map(|event| match event {
                Event::TaskUpdated { report } => Some(report),
                _ => None,
            })
            .collect()
    }

    pub fn final_report(&self) -> &TaskReport {
        self.reports().last().copied().expect("missing task report")
    }

    pub fn assert_not_complete(&self) {
        assert!(
            self.reports().len() >= 2,
            "expected initial and terminal task reports"
        );
        for report in self.reports() {
            assert_ne!(report.status, TaskStatus::Complete, "{report:#?}");
        }
        for event in &self.persisted {
            if let SessionEvent::TaskUpdated { report } = event {
                assert_ne!(report.status, TaskStatus::Complete, "{report:#?}");
            }
        }
    }

    pub fn assert_response_completed(&self) {
        assert!(
            self.events
                .iter()
                .any(|event| matches!(event, Event::TurnCompleted { .. })),
            "{:#?}",
            self.events
        );
        assert!(
            !self
                .events
                .iter()
                .any(|event| matches!(event, Event::Error(_) | Event::TurnAborted)),
            "{:#?}",
            self.events
        );
    }
}
