import { mount } from "svelte";
import App from "./App.svelte";
import { appInfo } from "./lib/commands";
import { applyPlatformClass, applyWindowMaterial } from "./lib/platform";
import "./styles/tokens.css";
import "./styles/base.css";
import "./styles/motion.css";
import "./styles/materials.css";
import "./styles/buttons.css";
import "./styles/kit.css";
import "./styles/kit-parts.css";
import "./styles/fields.css";
import "./styles/segmented.css";
import "./styles/panels.css";
import "./styles/popovers.css";
import "./styles/worktree-dialog.css";
import "./styles/shell-drawer.css";
import "./styles/agents.css";
import "./styles/agents-rows.css";
import "./styles/agents-jobs.css";
import "./styles/diff.css";
import "./styles/diff-view.css";
import "./styles/inspector.css";
import "./styles/inspector-outline.css";
import "./styles/inspector-reader.css";
import "./styles/palette.css";
import "./styles/settings.css";
import "./styles/settings-groups.css";
import "./styles/settings-rows.css";
import "./styles/settings-chips.css";
import "./styles/settings-notices.css";
import "./styles/settings-lists.css";
import "./styles/settings-providers.css";
import "./styles/settings-permissions.css";
import "./styles/settings-mcp.css";
import "./styles/settings-extensions.css";
import "./styles/settings-about.css";
import "./styles/settings-paths.css";
import "./styles/shell.css";
import "./styles/stage.css";
import "./styles/sidebar.css";
import "./styles/sidebar-projects.css";
import "./styles/sidebar-footer.css";
import "./styles/sidepanel.css";
import "./styles/plan-view.css";
import "./styles/pet-body.css";
import "./styles/pet-face.css";
import "./styles/pet-props.css";
import "./styles/pet-bubble.css";
import "./styles/pet-moves.css";
import "./styles/pet-keyframes.css";
import "./styles/pet-ui.css";
import "./styles/island.css";
import "./styles/island-card.css";
import "./styles/island-satellites.css";
import "./styles/context-card.css";
import "./styles/provider-form.css";
import "./styles/onboarding.css";
import "./styles/onboarding-choices.css";
import "./styles/onboarding-cards.css";
import "./styles/home.css";
import "./styles/inbox.css";
import "./styles/transcript.css";
import "./styles/transcript-blocks.css";
import "./styles/transcript-chrome.css";
import "./styles/transcript-work.css";
import "./styles/markdown.css";
import "./styles/tools.css";
import "./styles/receipt.css";
import "./styles/interaction.css";
import "./styles/interaction-planning.css";
import "./styles/composer.css";
import "./styles/composer-extras.css";
import "./styles/composer-pickers.css";
import "./styles/composer-popovers.css";

applyPlatformClass();
appInfo()
  .then((info) => applyWindowMaterial(info.nativeGlass))
  .catch(() => applyWindowMaterial(false));

const target = document.getElementById("root");
if (!target) throw new Error("missing #root");

mount(App, { target });

if (import.meta.env.DEV) void import("./lib/runtime/devChat").then((dev) => dev.installDevChat());
