// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Isolation } from "../Isolation";
import type { PermissionMode } from "../PermissionMode";
import type { ExtensionSource } from "./ExtensionSource";

export type AgentDef = { name: string, 
/**
 * When to use the agent; shown to the model choosing a subagent.
 */
description: string, 
/**
 * Allowed tools; `None` allows every tool.
 */
tools: Array<string> | null, disallowedTools: Array<string>, 
/**
 * `inherit`, an alias (`main`, `fast`, `review`), or a model id;
 * `None` inherits.
 */
model: string | null, permissionMode: PermissionMode | null, isolation: Isolation, maxTurns: number | null, color: string | null, 
/**
 * The system prompt (markdown body).
 */
prompt: string, source: ExtensionSource, };
