// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentSettings = { 
/**
 * Subagents running at once (at least 1).
 */
max_concurrent: number, 
/**
 * Nesting depth of subagents; 0 disables subagents.
 */
max_depth: number, 
/**
 * Model turns per agent run (at least 1).
 */
max_turns: number, 
/**
 * Stop the session at this spend; 0 disables the cap.
 */
session_cost_cap_usd: number, };
