// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[decisions.calibration.<question>]`
 */
export type CalibrationEntry = { 
/**
 * Divides the model's log-probabilities; above 1 softens an
 * over-confident question.
 */
temperature: number, 
/**
 * Confidence needed to act on this question; unset uses `threshold`.
 */
threshold: number | null, };
