// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckKind } from "../CheckKind";

export type CheckConfig = { id: string, 
/**
 * Display name; empty uses `id`.
 */
label: string, command: string, kind: CheckKind, 
/**
 * Working directory relative to the project root.
 */
cwd: string | null, timeout_secs: number, };
