// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionSource } from "./ExtensionSource";

export type CommandDef = { 
/**
 * Path under `commands/` without `.md`, with `/` written as `:`,
 * e.g. `frontend:component`.
 */
name: string, description: string, argumentHint: string | null, 
/**
 * Tool rules granted while the command runs.
 */
allowedTools: Array<string>, model: string | null, 
/**
 * Only the user may invoke the command, not the model.
 */
disableModelInvocation: boolean, 
/**
 * The prompt template (`$ARGUMENTS`, `$1`, ...).
 */
body: string, source: ExtensionSource, };
