// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CompatSettings = { 
/**
 * Also read `.claude/` folders and `CLAUDE.md` files.
 */
claude: boolean, };
