// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContextSettings = { 
/**
 * Compact when the context is this full, clamped to 50..=99.
 */
compact_at_percent: number, 
/**
 * Tool results kept verbatim when older ones are cleared.
 */
keep_recent_tool_results: number, 
/**
 * Include a repository map in the system prompt.
 */
repo_map: boolean, repo_map_chars: number, };
