// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DecisionRule = { 
/**
 * Shown in approvals and notices; the question when unset.
 */
name: string | null, 
/**
 * `PreToolUse` or `UserPromptSubmit`.
 */
event: string, 
/**
 * `PreToolUse` only: a regex over tool names, as in hooks; unset
 * matches every tool.
 */
matcher: string | null, 
/**
 * What to ask about the tool call or the message.
 */
question: string, 
/**
 * The possible answers; empty means yes or no.
 */
options: Array<string>, 
/**
 * The answers that trigger `action`; empty means `yes`, or the first
 * option.
 */
when: Array<string>, 
/**
 * `ask` (approve the tool call first, or have the agent ask you
 * before it changes anything), `notice`, or `remind` (a note to the
 * agent).
 */
action: string, };
