// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[decisions.loop_guard]`
 */
export type DecisionLoopGuardSettings = { 
/**
 * Reminders per turn before the loop guard asks you what to do,
 * 1 to 10.
 */
max_reminders: number, };
