// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[decisions.sidecar]`
 */
export type DecisionSidecarSettings = { 
/**
 * Shell command that starts laya-serve; when set it replaces
 * `endpoint`. The engine picks a free loopback port and sets
 * `LAYA_HOST`, `LAYA_PORT`, `LAYA_API_KEY` (random per launch),
 * `LAYA_CHECKPOINT` and `LAYA_MAX_LEN` for it.
 */
command: string | null, };
