// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[decisions.task_view]`
 */
export type DecisionTaskViewSettings = { 
/**
 * The newest exchanges before a new task that always stay in view,
 * 1 to 20.
 */
keep_recent_exchanges: number, };
