// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalibrationEntry } from "./CalibrationEntry";
import type { DecisionLoopGuardSettings } from "./DecisionLoopGuardSettings";
import type { DecisionPrefetchSettings } from "./DecisionPrefetchSettings";
import type { DecisionRoutingSettings } from "./DecisionRoutingSettings";
import type { DecisionRule } from "./DecisionRule";
import type { DecisionRuntime } from "./DecisionRuntime";
import type { DecisionSidecarSettings } from "./DecisionSidecarSettings";
import type { DecisionTaskViewSettings } from "./DecisionTaskViewSettings";

export type DecisionSettings = { 
/**
 * Base URL of the decision server; loopback only unless `allow_remote`.
 */
endpoint: string, 
/**
 * Environment variable holding the server's API key (e.g. Jev's).
 */
api_key_env: string | null, 
/**
 * Laya checkpoint the sidecar or native runtime loads: `english`,
 * `multilingual` or `typed-decisions`.
 */
checkpoint: string, 
/**
 * Tokens the checkpoint reads per question; longer inputs are cut.
 */
max_len: number, 
/**
 * Longest wait for an answer; a slower answer counts as no answer.
 */
timeout_ms: number, 
/**
 * Confidence (0 to 1) an answer needs before a feature acts on it.
 */
threshold: number, 
/**
 * Most questions sent in one request.
 */
max_batch: number, 
/**
 * Allow an endpoint that is not on this machine.
 */
allow_remote: boolean, runtime: DecisionRuntime, sidecar: DecisionSidecarSettings, 
/**
 * Save decision inputs and answers to a local dataset folder.
 */
record_dataset: boolean, 
/**
 * Question name to its calibration.
 */
calibration: { [key in string]: CalibrationEntry }, prefetch: DecisionPrefetchSettings, routing: DecisionRoutingSettings, loop_guard: DecisionLoopGuardSettings, task_view: DecisionTaskViewSettings, 
/**
 * `[[decisions.rules]]`; user and project rules add up.
 */
rules: Array<DecisionRule>, };
