// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[decisions.routing]`
 */
export type DecisionRoutingSettings = { 
/**
 * Let a new task (and a subagent whose model is `inherit`) run on
 * the fast model instead of the main one. Off: only the reasoning
 * effort is suggested.
 */
allow_model_switch: boolean, };
