// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DecisionPrefetchSettings = { 
/**
 * Most files attached at one task start.
 */
max_files: number, 
/**
 * Estimated tokens all attached files may take together; a file that
 * does not fit is skipped.
 */
max_tokens: number, };
