// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a definition was found; variants are ordered by precedence,
 * lowest first, and a higher scope replaces a same-named definition.
 */
export type ExtensionScope = "claudeUser" | "user" | "claudeProject" | "project";
