// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentDef } from "./AgentDef";
import type { CommandDef } from "./CommandDef";
import type { ExtensionError } from "./ExtensionError";
import type { OutputStyleDef } from "./OutputStyleDef";
import type { RuleDef } from "./RuleDef";
import type { SkillDef } from "./SkillDef";

/**
 * Every user-authored extension after precedence, each list sorted by name.
 */
export type Extensions = { agents: Array<AgentDef>, commands: Array<CommandDef>, skills: Array<SkillDef>, rules: Array<RuleDef>, outputStyles: Array<OutputStyleDef>, errors: Array<ExtensionError>, };
