// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A file that was skipped, with the reason.
 */
export type ExtensionError = { path: string, message: string, };
