// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionScope } from "./ExtensionScope";

export type ExtensionSource = { scope: ExtensionScope, path: string, };
