// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Features that share settings; the Experimental tab shows a group's
 * settings card while any of its features runs.
 */
export type FeatureGroup = "decisions";
