// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeatureGroup } from "./FeatureGroup";
import type { FeatureId } from "./FeatureId";
import type { FeatureStage } from "./FeatureStage";

export type FeatureSpec = { id: FeatureId, title: string, summary: string, stage: FeatureStage, group: FeatureGroup, 
/**
 * `shadow` is allowed: the feature runs and records, never acts.
 */
supportsShadow: boolean, 
/**
 * Built in this version. A registered feature that is not built yet
 * stays off and is not listed.
 */
available: boolean, owner: string, 
/**
 * The measurable bar for becoming Stable (results go in docs/status.md).
 */
graduationCriteria: string, };
