// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HookConfig = { 
/**
 * Regex over tool names for tool events; `None` matches every tool.
 */
matcher: string | null, command: string, timeout_secs: number, };
