// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstructionScope } from "./InstructionScope";

export type InstructionFile = { scope: InstructionScope, path: string, content: string, };
