// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A stored key as the settings screen may show it.
 */
export type KeyStatus = { hasKey: boolean, 
/**
 * The key's last four characters.
 */
hint: string | null, };
