// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayerScope } from "./LayerScope";

export type LayerInfo = { scope: LayerScope, path: string | null, 
/**
 * The file exists; for the env layer, an override variable is set.
 */
exists: boolean, 
/**
 * Why the layer was skipped.
 */
error: string | null, };
