// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayerInfo } from "./LayerInfo";
import type { Settings } from "./Settings";

export type LoadedSettings = { settings: Settings, 
/**
 * Lowest precedence first.
 */
layers: Array<LayerInfo>, warnings: Array<string>, };
