// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspServerConfig } from "./LspServerConfig";

export type LspSettings = { enabled: boolean, 
/**
 * A later layer's server replaces an earlier one with the same name.
 */
servers: { [key in string]: LspServerConfig }, };
