// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LspServerConfig = { command: string, args: Array<string>, 
/**
 * File extensions without the dot, e.g. `rs`.
 */
extensions: Array<string>, 
/**
 * Files marking a workspace root, e.g. `Cargo.toml`.
 */
root_markers: Array<string>, enabled: boolean, };
