// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpServerConfig = { 
/**
 * Executable of a stdio server. Exactly one of `command` and `url` is set.
 */
command: string | null, args: Array<string>, env: { [key in string]: string }, cwd: string | null, 
/**
 * Endpoint of a streamable HTTP server.
 */
url: string | null, headers: { [key in string]: string }, enabled: boolean, 
/**
 * Tools of this server hidden from the model.
 */
disabled_tools: Array<string>, timeout_secs: number, };
