// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MigrationOutcome = { migrated: boolean, 
/**
 * Copy of the v1 file, e.g. `config.v1.toml` beside `config.toml`.
 */
backup: string | null, 
/**
 * What changed meaning or was dropped.
 */
notes: Array<string>, };
