// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MigrationOutcome = { 
/**
 * A v2 file was written from a v1 file.
 */
migrated: boolean, 
/**
 * The v1 file that was imported; it is left unchanged.
 */
source: string | null, 
/**
 * What changed meaning or was dropped.
 */
notes: Array<string>, };
