// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Effort } from "../Effort";

export type ModelSettings = { 
/**
 * Model id of the main agent.
 */
main: string, 
/**
 * Model for titles, summaries, and quick subagents; `None` uses `main`.
 */
fast: string | null, 
/**
 * Model for review agents; `None` uses `main`.
 */
review: string | null, 
/**
 * Tried in order when the main model fails with a retryable error.
 */
fallbacks: Array<string>, effort: Effort | null, 
/**
 * Per-request output ceiling, clamped to 256..=200000.
 */
max_output_tokens: number, 
/**
 * Overrides the catalog's context window when set.
 */
context_window: number | null, };
