// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionSource } from "./ExtensionSource";

export type OutputStyleDef = { name: string, description: string, body: string, source: ExtensionSource, };
