// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionMode } from "../PermissionMode";

export type PermissionSettings = { mode: PermissionMode, 
/**
 * Rules such as `Read`, `Bash(cargo test:*)`, or `Edit(src/**)`.
 * Rule lists union across layers.
 */
allow: Array<string>, ask: Array<string>, deny: Array<string>, 
/**
 * Directories outside the project the agent may work in.
 */
additional_directories: Array<string>, 
/**
 * Run recognised read-only shell commands without asking.
 */
auto_allow_read_only_bash: boolean, };
