// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The pet's body color.
 */
export type PetLook = "pearl" | "mint" | "sky" | "lilac" | "peach" | "graphite";
