// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PetLook } from "./PetLook";

/**
 * `[ui.pet]`: the pet's name, its look, and whether it walks around the window.
 */
export type PetSettings = { name: string, look: PetLook, 
/**
 * At the lively level, the pet leaves the title bar to sit on the
 * composer and the panels while nothing needs it there.
 */
roam: boolean, };
