// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * USD per million tokens for one model id, overriding the catalog.
 */
export type PricingOverride = { input: number, output: number, cache_read: number | null, cache_write: number | null, };
