// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderKind } from "./ProviderKind";

export type ProviderSettings = { kind: ProviderKind, 
/**
 * API base URL, stored without a trailing slash.
 */
base_url: string, 
/**
 * Extra HTTP headers sent with every model request.
 */
headers: { [key in string]: string }, 
/**
 * Prompt caching; `None` enables it where the provider supports it.
 */
cache_control: boolean | null, };
