// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionSource } from "./ExtensionSource";

export type RuleDef = { name: string, description: string, 
/**
 * Validated gitignore-style globs for the paths the rule applies to.
 */
globs: Array<string>, 
/**
 * Attach to every request regardless of paths.
 */
alwaysApply: boolean, body: string, source: ExtensionSource, };
