// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which permission list a rule belongs to.
 */
export type RuleKind = "allow" | "ask" | "deny";
