// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Runs agent commands (Bash, background shells, checks) in an OS sandbox
 * that only lets them write inside the project, the additional
 * directories, temp directories, tool caches, and `extra_writable`.
 */
export type SandboxSettings = { enabled: boolean, 
/**
 * Off blocks every connection except to localhost.
 */
allow_network: boolean, 
/**
 * More writable directories; `~/` is the home directory and relative
 * paths resolve against the project root. Unions across layers.
 */
extra_writable: Array<string>, 
/**
 * Run sandboxed commands that would otherwise ask without asking;
 * deny and ask rules and plan mode still apply.
 */
auto_allow: boolean, };
