// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSettings } from "./AgentSettings";
import type { CompatSettings } from "./CompatSettings";
import type { ContextSettings } from "./ContextSettings";
import type { HookConfig } from "./HookConfig";
import type { LspSettings } from "./LspSettings";
import type { McpSettings } from "./McpSettings";
import type { ModelSettings } from "./ModelSettings";
import type { PermissionSettings } from "./PermissionSettings";
import type { PricingOverride } from "./PricingOverride";
import type { ProviderSettings } from "./ProviderSettings";
import type { ShellSettings } from "./ShellSettings";
import type { UiSettings } from "./UiSettings";
import type { VerificationSettings } from "./VerificationSettings";
import type { WebSettings } from "./WebSettings";

export type Settings = { model: ModelSettings, provider: ProviderSettings, permissions: PermissionSettings, context: ContextSettings, agents: AgentSettings, verification: VerificationSettings, 
/**
 * Hook event (see `HOOK_EVENTS`) to hooks run in order; lists
 * concatenate across layers.
 */
hooks: { [key in string]: Array<HookConfig> }, mcp: McpSettings, lsp: LspSettings, web: WebSettings, shell: ShellSettings, ui: UiSettings, compat: CompatSettings, 
/**
 * Model id to pricing, overriding the catalog.
 */
pricing: { [key in string]: PricingOverride }, };
