// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShellSettings = { 
/**
 * Shell executable; `None` detects one.
 */
path: string | null, 
/**
 * Variables passed through from the app's environment. Unions across layers.
 */
env_passthrough: Array<string>, 
/**
 * Variables set for every command.
 */
env: { [key in string]: string }, };
