// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionSource } from "./ExtensionSource";

export type SkillDef = { name: string, 
/**
 * When to use the skill; shown to the model.
 */
description: string, 
/**
 * Tool rules granted while the skill is active.
 */
allowedTools: Array<string>, 
/**
 * The skill directory, which holds any bundled files.
 */
dir: string, 
/**
 * Path of `SKILL.md`.
 */
file: string, source: ExtensionSource, };
