// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompanionLevel } from "./CompanionLevel";
import type { PetSettings } from "./PetSettings";
import type { TaskReportView } from "./TaskReportView";

export type UiSettings = { task_report_view: TaskReportView, 
/**
 * Output style name (from `output-styles/`); `None` is the default style.
 */
output_style: string | null, companion: CompanionLevel, pet: PetSettings, };
