// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VerificationMode } from "../VerificationMode";
import type { CheckConfig } from "./CheckConfig";

export type VerificationSettings = { mode: VerificationMode, 
/**
 * Automatic continuations after failed checks (at most 10).
 */
max_continuations: number, 
/**
 * Check kinds (`test`, `lint`, ...) or check ids run in auto/strict mode.
 */
auto_checks: Array<string>, 
/**
 * A later layer's check replaces an earlier one with the same `id`.
 */
checks: Array<CheckConfig>, };
