// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchBackend } from "./SearchBackend";

export type WebSettings = { search_backend: SearchBackend, 
/**
 * Base URL of the SearXNG instance.
 */
search_url: string | null, 
/**
 * Convert fetched HTML to markdown.
 */
fetch_extract: boolean, 
/**
 * Allow fetching loopback and private-network addresses.
 */
allow_private_network: boolean, };
