// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One agent run (the main agent or a spawned subagent).
 */
export type AgentId = string;
