// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { AgentStatus } from "./AgentStatus";
import type { Isolation } from "./Isolation";
import type { Usage } from "./Usage";
import type { WorktreeInfo } from "./WorktreeInfo";

export type AgentInfo = { agentId: AgentId, parentId: AgentId | null, 
/**
 * Definition name, e.g. "explore" or a custom agent.
 */
agentType: string, 
/**
 * Short task label supplied by the caller.
 */
description: string, model: string, background: boolean, isolation: Isolation, worktree: WorktreeInfo | null, status: AgentStatus, depth: number, startedAt: number, finishedAt: number | null, usage: Usage, costUsd: number, toolCalls: number, resultPreview: string | null, error: string | null, };
