// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { CallId } from "./CallId";
import type { Preview } from "./Preview";
import type { RequestId } from "./RequestId";
import type { JsonValue } from "./serde_json/JsonValue";

export type ApprovalRequest = { requestId: RequestId, agentId: AgentId, callId: CallId, tool: string, 
/**
 * One-line description, e.g. "Edit src/main.rs".
 */
title: string, input: JsonValue, preview: Preview | null, 
/**
 * Why the policy asked (matched rule, outside directory, ...).
 */
reason: string, suggestedRule: string | null, 
/**
 * False for targets outside allowed directories.
 */
canPersist: boolean, };
