// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The user's answer to an approval request.
 */
export type ApprovalDecision = { "type": "allowOnce" } | { "type": "allowSession", rule: string, } | { "type": "allowProject", rule: string, } | { "type": "deny", feedback: string | null, };
