// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Attachment = { "type": "image", mediaType: string, data: string, } | { "type": "file", path: string, };
