// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { CheckKind } from "./CheckKind";
import type { TestCounts } from "./TestCounts";

/**
 * One executed check. Fingerprints identify the workspace state before
 * and after the run; a later mutation makes the record stale.
 */
export type CheckRecord = { recordId: string, checkId: string, label: string, kind: CheckKind, command: string, cwd: string, agentId: AgentId, exitCode: number | null, passed: boolean, timedOut: boolean, startedAt: number, durationMs: number, tests: TestCounts | null, 
/**
 * Path of the full output artifact.
 */
artifact: string | null, fingerprintBefore: string, fingerprintAfter: string, outputTail: string, };
