// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A code checkpoint taken before a user turn.
 */
export type CheckpointId = string;
