// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckpointId } from "./CheckpointId";
import type { MessageId } from "./MessageId";

export type CheckpointInfo = { checkpointId: CheckpointId, 
/**
 * Restoring returns the code to its state before this user message.
 */
messageId: MessageId, createdAt: number, };
