// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { ApprovalDecision } from "./ApprovalDecision";
import type { Attachment } from "./Attachment";
import type { Effort } from "./Effort";
import type { JobId } from "./JobId";
import type { MessageId } from "./MessageId";
import type { PermissionMode } from "./PermissionMode";
import type { PlanDecision } from "./PlanDecision";
import type { QuestionAnswer } from "./QuestionAnswer";
import type { RequestId } from "./RequestId";
import type { RewindScope } from "./RewindScope";

export type Command = { "type": "submit", text: string, attachments: Array<Attachment>, } | { "type": "steer", text: string, } | { "type": "interrupt", text: string | null, } | { "type": "cancel" } | { "type": "resolveApproval", requestId: RequestId, decision: ApprovalDecision, } | { "type": "answerQuestion", requestId: RequestId, answers: Array<QuestionAnswer> | null, } | { "type": "resolvePlan", requestId: RequestId, decision: PlanDecision, } | { "type": "setMode", mode: PermissionMode, } | { "type": "setModel", model: string, } | { "type": "setEffort", effort: Effort | null, } | { "type": "compact", instructions: string | null, } | { "type": "rewind", messageId: MessageId, scope: RewindScope, } | { "type": "killJob", jobId: JobId, } | { "type": "applyAgentChanges", agentId: AgentId, } | { "type": "discardAgentChanges", agentId: AgentId, } | { "type": "runCommand", name: string, args: string, } | { "type": "shell", command: string, } | { "type": "editQueue", queued: Array<string>, } | { "type": "reloadExtensions" } | { "type": "shutdown" };
