// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageId } from "./MessageId";

export type CompactionMarker = { 
/**
 * First message kept verbatim after the summary.
 */
keepFrom: MessageId | null, summary: string, tokensBefore: number, tokensAfter: number, createdAt: number, };
