// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallId } from "./CallId";
import type { MediaSource } from "./MediaSource";
import type { ToolResultPart } from "./ToolResultPart";
import type { JsonValue } from "./serde_json/JsonValue";

export type ContentBlock = { "type": "text", text: string, } | { "type": "image", source: MediaSource, } | { "type": "document", source: MediaSource, title: string | null, } | { "type": "thinking", text: string, signature: string | null, } | { "type": "redactedThinking", data: string, } | { "type": "toolUse", id: CallId, name: string, input: JsonValue, } | { "type": "toolResult", toolUseId: CallId, content: Array<ToolResultPart>, isError: boolean, };
