// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Token usage by prompt layer, for `/context`.
 */
export type ContextBreakdown = { system: number, tools: number, instructions: number, messages: number, total: number, limit: number, };
