// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { AgentInfo } from "./AgentInfo";
import type { ApprovalRequest } from "./ApprovalRequest";
import type { CallId } from "./CallId";
import type { CheckRecord } from "./CheckRecord";
import type { CheckpointInfo } from "./CheckpointInfo";
import type { CompactionMarker } from "./CompactionMarker";
import type { ContextBreakdown } from "./ContextBreakdown";
import type { Effort } from "./Effort";
import type { JobInfo } from "./JobInfo";
import type { Message } from "./Message";
import type { MessageId } from "./MessageId";
import type { NoticeLevel } from "./NoticeLevel";
import type { PermissionMode } from "./PermissionMode";
import type { Question } from "./Question";
import type { RequestId } from "./RequestId";
import type { SessionSnapshot } from "./SessionSnapshot";
import type { SessionStatus } from "./SessionStatus";
import type { TodoItem } from "./TodoItem";
import type { ToolStatus } from "./ToolStatus";
import type { TurnId } from "./TurnId";
import type { TurnRecord } from "./TurnRecord";
import type { Usage } from "./Usage";
import type { VerificationOutcome } from "./VerificationOutcome";
import type { JsonValue } from "./serde_json/JsonValue";

export type Event = { "type": "snapshot", snapshot: SessionSnapshot, } | { "type": "statusChanged", status: SessionStatus, } | { "type": "userMessage", message: Message, turnId: TurnId | null, steering: boolean, } | { "type": "turnStarted", turnId: TurnId, messageId: MessageId, } | { "type": "turnFinished", turn: TurnRecord, } | { "type": "assistantStarted", agentId: AgentId, messageId: MessageId, } | { "type": "textDelta", agentId: AgentId, messageId: MessageId, text: string, } | { "type": "thinkingDelta", agentId: AgentId, messageId: MessageId, text: string, } | { "type": "assistantFinished", agentId: AgentId, message: Message, } | { "type": "toolStarted", agentId: AgentId, callId: CallId, tool: string, title: string, input: JsonValue, } | { "type": "toolProgress", agentId: AgentId, callId: CallId, text: string, } | { "type": "toolFinished", agentId: AgentId, callId: CallId, status: ToolStatus, summary: string, 
/**
 * Truncated result text for the tool card.
 */
output: string, durationMs: number, } | { "type": "approvalRequested", request: ApprovalRequest, } | { "type": "approvalResolved", requestId: RequestId, allowed: boolean, } | { "type": "questionAsked", requestId: RequestId, agentId: AgentId, questions: Array<Question>, } | { "type": "questionResolved", requestId: RequestId, answered: boolean, } | { "type": "planProposed", requestId: RequestId, agentId: AgentId, plan: string, } | { "type": "planResolved", requestId: RequestId, approved: boolean, } | { "type": "todosUpdated", agentId: AgentId, todos: Array<TodoItem>, } | { "type": "agentStarted", info: AgentInfo, } | { "type": "agentUpdated", info: AgentInfo, } | { "type": "jobUpdated", job: JobInfo, } | { "type": "usageUpdated", agentId: AgentId, 
/**
 * Cumulative usage of this agent.
 */
usage: Usage, sessionUsage: Usage, costUsd: number, contextTokens: number, contextLimit: number, } | { "type": "modeChanged", mode: PermissionMode, } | { "type": "modelChanged", model: string, } | { "type": "effortChanged", effort: Effort | null, } | { "type": "compacted", marker: CompactionMarker, } | { "type": "checkpointCreated", checkpoint: CheckpointInfo, } | { "type": "checkRecorded", record: CheckRecord, } | { "type": "verificationChanged", outcome: VerificationOutcome, } | { "type": "hookRan", hookEvent: string, command: string, blocked: boolean, message: string | null, } | { "type": "commandOutput", name: string, markdown: string, } | { "type": "contextReport", breakdown: ContextBreakdown, } | { "type": "notice", level: NoticeLevel, text: string, } | { "type": "retrying", attempt: number, delayMs: number, reason: string, } | { "type": "titleChanged", title: string, } | { "type": "queueChanged", queued: Array<string>, } | { "type": "trustRequired", projectRoot: string, defines: Array<string>, } | { "type": "error", message: string, };
