// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Event } from "./Event";
import type { SessionId } from "./SessionId";

export type EventEnvelope = { sessionId: SessionId, seq: number, event: Event, };
