// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { JobId } from "./JobId";
import type { JobKind } from "./JobKind";
import type { JobStatus } from "./JobStatus";

export type JobInfo = { jobId: JobId, kind: JobKind, 
/**
 * Command line or agent description.
 */
label: string, 
/**
 * Agent that started the job.
 */
owner: AgentId, 
/**
 * For agent jobs, the background agent's id.
 */
agentId: AgentId | null, status: JobStatus, exitCode: number | null, startedAt: number, finishedAt: number | null, 
/**
 * Last few KiB of output for the jobs panel.
 */
outputTail: string, };
