// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A background job: a shell process or a background agent.
 */
export type JobId = string;
