// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MediaSource = { "kind": "base64", mediaType: string, data: string, } | { "kind": "url", url: string, };
