// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentBlock } from "./ContentBlock";
import type { MessageId } from "./MessageId";
import type { Role } from "./Role";

export type Message = { id: MessageId, role: Role, content: Array<ContentBlock>, createdAt: number, };
