// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pricing } from "./Pricing";

export type ModelInfo = { 
/**
 * The id as its provider lists it; OpenRouter ids are `vendor/model`.
 */
id: string, name: string, 
/**
 * models.dev provider id (`openrouter`, `anthropic`, `opencode`, ...).
 */
provider: string, 
/**
 * Tokens; 0 when unknown.
 */
contextWindow: number, 
/**
 * Tokens; 0 when unknown.
 */
maxOutput: number, pricing: Pricing | null, tools: boolean, vision: boolean, reasoning: boolean, };
