// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { Question } from "./Question";
import type { RequestId } from "./RequestId";

export type PendingQuestion = { requestId: RequestId, agentId: AgentId, questions: Array<Question>, };
