// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { RequestId } from "./RequestId";

export type PendingPlan = { requestId: RequestId, agentId: AgentId, plan: string, };
