// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionMode } from "./PermissionMode";

export type PlanDecision = { "type": "approve", mode: PermissionMode, editedPlan: string | null, } | { "type": "revise", feedback: string, };
