// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Rich detail rendered by the approval card.
 */
export type Preview = { "type": "diff", path: string, diff: string, } | { "type": "command", command: string, description: string | null, } | { "type": "text", text: string, };
