// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Prices in USD per million tokens.
 */
export type Pricing = { input: number, output: number, cacheRead: number, cacheWrite: number, };
