// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QuestionAnswer = { 
/**
 * The question text being answered.
 */
question: string, 
/**
 * Selected option labels, or a single custom answer.
 */
answers: Array<string>, };
