// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuestionOption } from "./QuestionOption";

export type Question = { question: string, 
/**
 * Short chip label (max ~12 characters).
 */
header: string, options: Array<QuestionOption>, multiSelect: boolean, };
