// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A pending user interaction: approval, question, or plan review.
 */
export type RequestId = string;
