// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { Effort } from "./Effort";

/**
 * A routing choice made when a task started (`decisions_routing`): the
 * main agent's new task, or a subagent whose model is `inherit`. The
 * transcript shows it as a chip.
 */
export type RouteInfo = { agentId: AgentId, 
/**
 * The reasoning effort chosen; `None` leaves the session's.
 */
effort: Effort | null, 
/**
 * The model chosen (main or fast); `None` leaves the session's.
 */
model: string | null, 
/**
 * Why, in a few words ("complex task, confidence 0.91").
 */
reason: string, };
