// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Effort } from "./Effort";
import type { PermissionMode } from "./PermissionMode";
import type { SessionId } from "./SessionId";

export type SessionInfo = { sessionId: SessionId, title: string | null, projectRoot: string, model: string, mode: PermissionMode, effort: Effort | null, createdAt: number, updatedAt: number, 
/**
 * Imported from a v1 session file.
 */
legacy: boolean, };
