// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionId } from "./SessionId";
import type { TurnOutcome } from "./TurnOutcome";

export type SessionSummary = { sessionId: SessionId, title: string | null, projectRoot: string, createdAt: number, updatedAt: number, messageCount: number, costUsd: number, lastOutcome: TurnOutcome | null, 
/**
 * A v1 file not yet imported.
 */
legacy: boolean, };
