// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A conversation session (bare ULID, compatible with v1 file names).
 */
export type SessionId = string;
