// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SuggestionKind } from "./SuggestionKind";

/**
 * An action a decision use offers as a card (plan first, save a rule,
 * run a review). Nothing happens until the user picks it; the answer
 * comes back as `Command::ResolveSuggestion`.
 */
export type Suggestion = { 
/**
 * `<feature id>:<input fingerprint>`, unique within the session.
 */
suggestionId: string, kind: SuggestionKind, };
