// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SuggestionKind = { "type": "planFirst" } | { "type": "saveRule", rule: string, } | { "type": "review", areas: Array<string>, paths: Array<string>, };
