// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageId } from "./MessageId";

/**
 * `decisions_task_view`: earlier exchanges set aside when a new task
 * started. The transcript shows a divider before `boundary` whose
 * "Include full history" action sends `Command::IncludeFullHistory`.
 */
export type TaskViewInfo = { 
/**
 * The user message that started the task.
 */
boundary: MessageId, 
/**
 * How many earlier exchanges were set aside.
 */
setAside: number, 
/**
 * Their estimated size in tokens.
 */
tokens: number, 
/**
 * The user brought the full history back; the view no longer applies.
 */
restored: boolean, createdAt: number, };
