// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TodoStatus } from "./TodoStatus";

export type TodoItem = { content: string, 
/**
 * Present-continuous label shown while in progress ("Running tests").
 */
activeForm: string, status: TodoStatus, };
