// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaSource } from "./MediaSource";

export type ToolResultPart = { "type": "text", text: string, } | { "type": "image", source: MediaSource, };
