// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a finished turn went, as the decision model judged it
 * (`decisions_pet_mood`); the pet shows it beside the turn's outcome.
 */
export type TurnTone = "smooth" | "struggling" | "blocked" | "done_well";
