// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageId } from "./MessageId";
import type { TurnId } from "./TurnId";
import type { TurnOutcome } from "./TurnOutcome";
import type { Usage } from "./Usage";
import type { VerificationOutcome } from "./VerificationOutcome";

export type TurnRecord = { turnId: TurnId, 
/**
 * The user message that started the turn.
 */
messageId: MessageId, outcome: TurnOutcome, verification: VerificationOutcome, usage: Usage, costUsd: number, startedAt: number, finishedAt: number, };
