// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TurnOutcome = { "type": "completed" } | { "type": "cancelled" } | { "type": "failed", message: string, } | { "type": "budgetExhausted", reason: string, } | { "type": "interrupted" };
