// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the agent's final message claimed while no check backed the turn
 * (`decisions_completion_check`). It never changes the turn's badge.
 */
export type UncheckedClaim = { 
/**
 * The message says the work is complete.
 */
done: boolean, 
/**
 * The message says tests or checks passed.
 */
checks: boolean, };
