// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Urgency } from "./Urgency";

/**
 * The urgency of one inbox item.
 */
export type UrgencyInfo = { 
/**
 * The request id of an approval, question or plan, or `notice:<text>`
 * for a notice.
 */
key: string, urgency: Urgency, };
