// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VerificationOutcome = { "status": "notApplicable" } | { "status": "unverified", reason: string, } | { "status": "verified", checks: Array<string>, } | { "status": "failed", reason: string, };
