// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorktreeState } from "./WorktreeState";

export type WorktreeInfo = { path: string, branch: string, 
/**
 * Commit the worktree was created from.
 */
base: string, state: WorktreeState, filesChanged: number, diffstat: string, };
